import type { SkillDefinition, WorkflowDefinition } from "../types/index.js";

export function learnPrompt(args: string): string {
  const value = args.trim();
  const block = value ? value : "(none)";
  return [
    "<learn_request>",
    "<summary>",
    "You MUST document session findings and workarounds.",
    "You SHOULD append 1-3 concise lines to root or create a nested AGENTS.md.",
    "Findings MUST be captured from non-obvious fixes or decisions.",
    "</summary>",
    "<user_guidelines>",
    block,
    "</user_guidelines>",
    "<objective>",
    "Capture critical why-decisions, workarounds, or fixes from this session.",
    "You MUST identify findings from current context and user guidelines when present.",
    "</objective>",
    "<instructions>",
    "1. Identify findings: You MUST analyze the session/task for friction points or non-obvious fixes.",
    "2. Auto-detect scope: You MUST determine whether findings are nested-directory-specific or repository-wide.",
    "3. Distill lesson: You MUST extract findings into 1-2 non-verbose lines and SHOULD match existing documentation style.",
    "4. Apply: You MUST append to root or chosen nested AGENTS.md. If none exists in chosen directory, you MUST create a minimalist AGENTS.md containing only the new findings.",
    "</instructions>",
    "<rules>",
    "- MUST be extremely concise (1-2 lines of new content).",
    "- MUST focus on how to avoid this issue next time.",
    "- MUST NOT use generic preambles or repeated information.",
    "</rules>",
    "</learn_request>",
  ].join("\n");
}

export const WORKFLOW_CREATE_PROMPT = [
  "<workflow_create_request>",
  "<objective>",
  "Document this session as a reusable workflow and enforce usage guidance via AGENTS.md.",
  "</objective>",
  "<format_requirements>",
  "You MUST follow RFC 2119 / RFC 8174 keyword semantics.",
  "You SHOULD use concise XML tags where this improves execution clarity.",
  "</format_requirements>",
  "<instructions>",
  "1. Discovery: You SHOULD inspect <available_workflows> first and read existing workflow files to avoid duplicates.",
  "2. Authoring: You MUST use workflows_create to create or update a workflow in ./.pi/workflows/<name>/SKILL.md.",
  "3. Repository alignment: You MUST ensure commands, paths, and assumptions match current repository standards.",
  "4. Content quality: You MUST include prerequisites, ordered steps, expected outcomes, and failure recovery notes for relevant edge cases.",
  "5. Scope: You SHOULD update the most specific AGENTS.md in the directory hierarchy where the work occurred (do not update repository root unless the workflow is truly global).",
  "6. Rule format: You MUST add this exact line before listing workflow names:",
  '   "When operating in this directory you MUST consider loading these workflows:"',
  "</instructions>",
  "<rules>",
  "- MUST persist reusable process knowledge via workflows_create.",
  "- MUST use the exact required AGENTS.md phrasing.",
  "- MUST keep AGENTS.md edits minimal and targeted.",
  "- MAY refine an existing workflow instead of creating a duplicate.",
  "</rules>",
  "</workflow_create_request>",
].join("\n");

export const SKILL_CREATE_PROMPT = [
  "<skill_create_request>",
  "<objective>",
  "Create a reusable skill with strong discovery metadata and deterministic execution guidance.",
  "</objective>",
  "<format_requirements>",
  "You MUST follow RFC 2119 / RFC 8174 keyword semantics.",
  "You MUST use concise XML tags and structure, consistent with this request format.",
  "</format_requirements>",
  "<instructions>",
  "1. Scope: You SHOULD prefer global skills at ~/.pi/agent/skills/<name>/SKILL.md unless project-local scope is explicitly required.",
  "2. Frontmatter: You MUST include valid SKILL.md frontmatter with name and description.",
  "3. Discovery quality: Description MUST be self-contained with capabilities, proactive trigger contexts, and concise action-mapped examples (query -> action).",
  "4. Body quality: You MUST include deterministic setup/usage/verification guidance with explicit failure recovery for relevant edge cases.",
  "5. Structure: You MAY add references/*.md for detailed variants and scripts/ for repeated or fragile steps that SHOULD be automated.",
  "</instructions>",
  "</skill_create_request>",
].join("\n");

export function refineWorkflowPrompt(workflow: WorkflowDefinition): string {
  return [
    "<workflow_refine_request>",
    `<name>${workflow.name}</name>`,
    `<location>${workflow.location}</location>`,
    "<objective>",
    "Refine this workflow for deterministic execution, current-repo alignment, and edge-case coverage.",
    "</objective>",
    "<format_requirements>",
    "You MUST follow RFC 2119 / RFC 8174 keyword semantics.",
    "You MUST use concise XML tags and structure, consistent with this request format.",
    "</format_requirements>",
    "<content_requirements>",
    "You MUST assess whether this workflow is up-to-date with current repository standards and conventions.",
    "You MUST update stale steps, commands, paths, and assumptions.",
    "You MUST improve ordered execution clarity and verification criteria.",
    "You MUST assess edge cases and failure modes and include concrete recovery steps where needed.",
    "You MUST preserve workflow intent while improving reliability and maintainability.",
    "</content_requirements>",
    "<constraints>",
    "This workflow MUST remain a single markdown document.",
    "</constraints>",
    "<acceptance_checks>",
    "Workflow steps SHOULD execute correctly in the current repository state.",
    "Edge-case handling MUST be explicit for high-risk or common failure paths.",
    "</acceptance_checks>",
    "</workflow_refine_request>",
  ].join("\n");
}

export function appendWorkflowAgentsPrompt(workflow: WorkflowDefinition): string {
  return [
    "<workflow_append_agents_request>",
    `<name>${workflow.name}</name>`,
    `<location>${workflow.location}</location>`,
    "<requirements>",
    "You MUST locate the most specific applicable AGENTS.md for this workflow scope.",
    "You MUST verify whether this workflow is already listed before any edits.",
    "You MUST keep edits minimal and idempotent.",
    "You MUST include the exact heading line before entries:",
    "When operating in this directory you MUST consider loading these workflows:",
    "</requirements>",
    "</workflow_append_agents_request>",
  ].join("\n");
}

export function refineSkillPrompt(skill: SkillDefinition): string {
  return [
    "<skill_refine_request>",
    `<name>${skill.name}</name>`,
    `<location>${skill.location}</location>`,
    "<objective>",
    "Refine this skill for high-signal discovery and deterministic execution with minimal token overhead.",
    "</objective>",
    "<format_requirements>",
    "You MUST follow RFC 2119 / RFC 8174 keyword semantics.",
    "You MUST use concise XML tags and structure, consistent with this request format.",
    "</format_requirements>",
    "<frontmatter_requirements>",
    "You MUST preserve required SKILL.md frontmatter fields and keep name stable unless user requests rename.",
    "You MUST make description self-contained: capabilities, proactive trigger contexts, and concrete examples.",
    "You MUST keep examples concise and action-mapped (query -> action), without conversational filler.",
    "</frontmatter_requirements>",
    "<body_requirements>",
    "You MUST improve clarity, deterministic execution, and verification guidance.",
    "You SHOULD include setup, usage, and failure recovery guidance only where it is operationally necessary.",
    "You MAY add references under references/*.md when detail would clutter SKILL.md.",
    "You MAY add executable helpers under scripts/ when repeated or fragile steps require automation.",
    "</body_requirements>",
    "<acceptance_checks>",
    "Description alone SHOULD justify loading the skill.",
    "Instructions MUST be executable step-by-step without ambiguity.",
    "</acceptance_checks>",
    "</skill_refine_request>",
  ].join("\n");
}
